# YAML for launching peer0 netflix
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peer0-netflix-myapp
  labels:
    run: peer0-netflix-myapp
spec:
  serviceName: peer0-netflix-myapp
  replicas: 1
  selector:
    matchLabels:
      run: peer0-netflix-myapp
  template:
    metadata:
      labels:
        run: peer0-netflix-myapp
    spec:
      containers:
      - name: peer0-netflix-myapp
        # Image used
        image: hyperledger/fabric-peer
        env:
          - name: FABRIC_CFG_PATH
            value: /etc/hyperledger/fabric
          - name: FABRIC_LOGGING_SPEC
            value: DEBUG          
          - name: CORE_PEER_ID
            value: peer0-netflix-myapp
          - name: CORE_PEER_ADDRESS
            value: peer0-netflix-myapp:7051
            #value: 0.0.0.0:7051 
          - name: CORE_PEER_LISTENADDRESS
            value: 0.0.0.0:7051
          - name: CORE_PEER_CHAINCODEADDRESS
            value: peer0-netflix-myapp:7052
          - name: CORE_PEER_CHAINCODELISTENADDRESS
            value: 0.0.0.0:7052
          - name: CORE_PEER_LOCALMSPID
            value: netflixMSP
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: CORE_PEER_PROFILE_ENABLED
            value: "true"
          - name: CORE_PEER_TLS_CERT_FILE
            value: /etc/hyperledger/fabric/tls/server.crt
          - name: CORE_PEER_TLS_KEY_FILE
            value: /etc/hyperledger/fabric/tls/server.key
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: /etc/hyperledger/fabric/tls/ca.crt
          - name: CORE_VM_ENDPOINT
            value: unix:///host/var/run/docker.sock
          - name: ORDERER_ADDRESS
            value: orderer-myapp:7050
          - name: ORG_CONTEXT
            value: netflix
            
        workingDir: /etc/hyperledger/fabric
        
        volumeMounts:
        - name: peer0-netflix-myapp-ledger
          mountPath: /var/ledger
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: my-pvc-nfs
          mountPath: /etc/hyperledger/fabric/msp
          subPath: crypto-config/peerOrganizations/netflix-myapp/peers/peer0-netflix-myapp/msp
        - name: my-pvc-nfs
          mountPath: /etc/hyperledger/fabric/tls
          subPath: crypto-config/peerOrganizations/netflix-myapp/peers/peer0-netflix-myapp/tls
        - name: my-pvc-nfs
          mountPath: /etc/hyperledger/fabric/users
          subPath: crypto-config/peerOrganizations/netflix-myapp/users
        - name: my-pvc-nfs
          mountPath: /etc/hyperledger/fabric/chaincode
          subPath: chaincode
        - name: my-pvc-nfs
          mountPath: /etc/hyperledger/fabric/channel-artifacts
          subPath: channel-artifacts
        - name: my-pvc-nfs
          mountPath: /var/hyperledger/production
          subPath: crypto-config/peerOrganizations/netflix-myapp/peers/peer0-netflix-myapp      
        - name: my-pvc-nfs
          mountPath: /etc/hyperledger/fabric/crypto
          subPath: crypto-config 
          
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs
          
  volumeClaimTemplates:
  - metadata: 
      name: peer0-netflix-myapp-ledger
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: general
      resources:
        requests:
          storage: 1Gi

---
# Expose the port 7051 as ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: peer0-netflix-myapp

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    run: peer0-netflix-myapp

  ports:
    - name: peer0-netflix-myapp
      port: 7051
    - name: peer0-netflix-myapp-cc
      port: 7052

  type: ClusterIP

---
# Expose the port 7051 as node port -  NEEDED if you
# are interested in connecting to the Pods from the Host
# machine - keep in mind you would need the IP for the node
# port service
apiVersion: v1
kind: Service
metadata:
  name: peer0-netflix-myapp-nodeport

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    run: peer0-netflix-myapp

  ports:
    - name: peer0-netflix-myapp-nodeport-7051
      port: 30751
      nodePort: 30751
    - name: peer0-netflix-myapp-cc-nodeport-7052
      port: 30752
      nodePort: 30752

  type: NodePort
